# Generated by Django 3.0.3 on 2020-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commented_by',
        ),
    ]
