# Generated by Django 3.0.3 on 2020-03-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200328_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_commented']},
        ),
    ]
