# Generated by Django 3.0.3 on 2020-04-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200329_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
