# Generated by Django 3.0.3 on 2020-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
