# Generated by Django 3.0.7 on 2020-08-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200804_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1),
        ),
    ]
