# Generated by Django 3.0.7 on 2020-08-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200805_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
    ]
