# Generated by Django 3.0.3 on 2020-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200421_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Django', 'django'), ('Python', 'python')], max_length=30),
        ),
    ]
