# Generated by Django 3.0.7 on 2020-08-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
    ]
