# Generated by Django 3.0.7 on 2020-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='truncated_content',
            field=models.CharField(default='Truncated content', max_length=100),
        ),
    ]
