# Generated by Django 3.0.7 on 2020-08-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_truncated_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], db_index=True, default='D', max_length=1),
        ),
    ]
