# Generated by Django 3.0.3 on 2020-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200421_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Django', 'django'), ('Python', 'python'), ('Other', 'other')], max_length=30),
        ),
    ]
