# Generated by Django 3.0.7 on 2020-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200812_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='truncated_content',
            field=models.CharField(default='Truncated content', max_length=200),
        ),
    ]
